import ClientHeader from "@/client-header";
import Header from "@/header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-blue-700 w-full grid gap-10 ">
          <Header />
          <ClientHeader />
          {children}
        </div>
      </body>
    </html>
  );
}
